# Generated by Django 3.1.2 on 2020-10-24 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloomapp', '0002_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomapp.groups')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloomapp.account')),
            ],
        ),
    ]
