# Generated by Django 3.1.2 on 2020-10-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloomapp', '0004_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bloomapp.groups'),
        ),
    ]
